# frozen_string_literal: true

source "https://rubygems.org"

gem "debug", "~> 1.7"
gem "dry-auto_inject", "~> 1.0"
gem "dry-container", "~> 0.11.0"
gem "dry-configurable"
gem "dry-logger", "~> 1.0", ">= 1.0.3"
gem "dry-monads", "~> 1.6"
gem "dry-transaction", "~> 0.15.0"
gem "faraday", "~> 2.7", ">= 2.7.2"
gem "hiredis"
gem "puma", "~> 6.0"
gem "redis", "~> 4.0"
gem "rubocop", "~> 1.39"
gem "rubocop-rspec", "~> 2.15"
gem "sequel", "~> 5.63"
gem "sidekiq", "~> 6.5", ">= 6.5.6"
gem "sidekiq-cron", "~> 1.7"
gem "sinatra", "~> 3.0", ">= 3.0.4"
gem "sqlite3", "~> 1.5", ">= 1.5.4"
